export const REQUEST_RECEIVED = "REQUEST_RECEIVED";
export const REQUEST_REJECTED = "REQUEST_REJECTED";
export const REQUEST_ACCEPTED = "REQUEST_ACCEPTED";
export const MATCH_SUCCESS = "MATCH_SUCCESS";
